### ISSUE TITLE
TODOS aus der Doku

### ISSUE THREAD

**Issue by jangruebener** [DHBWMannheim/learninganalystics#28]
Aus der Doku entnommene offene TODOs:
- [x] Nutzerhandbuch --> @Michi0400 
- [x] Konzeption: Thin-Client, Cloud Computing, Serverless Computing --> @Patrickmischka 
- [x] ER-Modell Datenstrukturen --> @Ermodo @aaronschweig 
- [x] Konzeption Übersetzung --> @Michi0400 
- [x] Anforderung Übersetzung --> @jangruebener; 
- [x] Gibt es einen Datenexport zur Auswertung für Dozenten? --> #33 
- [x] Theorieteil für Anforderungsanalyse Karteikarten verschieben --> @jangruebener 
- [x] Die haben auch noch den ganzen Lebenszyklus von React erklärt wtf= --> Machen wir nicht. Sind ja nicht behämmert.
- [x] Wasserfall / Agile --> @jangruebener 
- [x] Konzeption Nutzenanalyse + Überleitung? --> N.A depricated
- [x] Wie werden Kurse erstellt? --> Wird im Nutzerhandbuch abgedeckt
- [x] Todos und index-cards auch löschbar und alles, Wie technisch? --> Machen wir im Nutzerhandbuch
- [x] Doku über Authentifizierung --> Authentifizierung in Abschnitt 3.2.2 vorhanden, falls wir noch mehr umfang brauchen kann man das easy erweitern
- [x] Graphische Darstellung der Prozesse @aaronschweig @jangruebener 
- [x] Können Wir vielleicht noch einen User Acceptance Test machen?  --> Nope
- [x] Was soll noch alles in die Dokumentation? Auch sowas wie Quickstart und Ordneraufbau? --> 1 Seite zum Thema Ordnerstruktur @Michi0400 
- Angular differential loading und so zeug? --> TBD.
- Mehr Anforderungen Modell View Controller schreiben --> TBD.
- Lighthouse, Offline --> TBD.
- Verschlüsselung, Kompression, h2 Protokoll --> TBD.

**Comment by jangruebener** [comment]
- Können Wir vielleicht noch einen User Acceptance Test machen?  --> Nope
- Gibt es einen Datenexport zur Auswertung für Dozenten? --> #33 
- Theorieteil für Anforderungsanalyse Karteikarten verschieben --> @jangruebener 
- Was soll noch alles in die Dokumentation? Auch sowas wie Quickstart und Ordneraufbau? --> 1 Seite zum Thema Ordnerstruktur @Michi0400 
- Angular differential loading und so zeug? --> TBD.
- Anforderung und Konzeption Übersetzung --> Anforderung: @jangruebener; Konzeption: @Michi0400 
- Die haben auch noch den ganzen Lebenszyklus von React erklärt wtf= --> Machen wir nicht. Sind ja nicht behämmert.
- Wasserfall / Agile --> @jangruebener 
- Konzeption: Thin-Client, Cloud Computing, Serverless Computing --> @Patrickmischka 
- Konzeption Nutzenanalyse + Überleitung? --> N.A depricated
- Mehr Anforderungen Modell View Controller schreiben --> TBD.
- Wie werden Kurse erstellt? --> Wird im Nutzerhandbuch abgedeckt
- ER-Modell Datenstrukturen --> @Ermodo @aaronschweig 
- Todos und index-cards auch löschbar und alles, Wie technisch? --> Machen wir im Nutzerhandbuch
- Doku über Authentifizierung --> Authentifizierung in Abschnitt 3.2.2 vorhanden, falls wir noch mehr umfang brauchen kann man das easy erweitern
- Graphische Darstellung der Prozesse @aaronschweig @jangruebener 
- Lighthouse, Offline --> TBD.
- Verschlüsselung, Kompression, h2 Protokoll --> TBD.
- Nutzerhandbuch --> @Michi0400

**Comment by jangruebener** [comment]
Absprache 08.03.2021: Alle mit TBD- gelabelten Punkte halten wir uns mal offen falls wir noch Inhalte brauchen

**Comment by jangruebener** [comment]
Ich hab jetzt nur was über unser Vorgehen und agile bzw. Scrum geschrieben. Das Wasserfallmodell habe ich jetzt erstmal etwas außen vor gelassen. Könnt ja mal draufschauen, ob das für euch so passt oder ob ihr das gerne noch ergänzt hättet.

**Comment by jangruebener** [comment]
Wie ist denn hier bei den offenen Todos der Stand?

**Comment by Ermodo** [comment]
@jangruebener wollen wir da am Montag vielleicht nochmal zusammen drüber schauen?

**Comment by jangruebener** [comment]
> @jangruebener wollen wir da am Montag vielleicht nochmal zusammen drüber schauen?

Können wir gerne machen. Stellst du uns einen Termin ein? Danke :)
