### ISSUE TITLE
Regeln in Firebase hinterlegen

### ISSUE THREAD

**Issue by aaronschweig** [DHBWMannheim/learninganalystics#32]
Ich weiß nicht zu 100%, ob das nicht schon erledigt wurde, aber müssen nicht evtl. noch Regeln in Firebase hinterlegt werden, dass die Ressourcen nicht nur frontendseitig geschützt sind?

Wenn es noch gemacht werden müsste, könnte ich mich dazu Bereiterklären, diese zu hinterlegen. Ich bräuchte dafür nur Zugriff auf das Firebase Projekt und evtl. 15 min der Zeit von jemanden, der die genaue Datenstruktur des Systems kennt!

FYI @jangruebener @Ermodo

**Comment by jangruebener** [comment]
Done
