### ISSUE TITLE
Überarbeiten der Index-Cards

### ISSUE THREAD

**Issue by aaronschweig** [DHBWMannheim/learninganalystics#43]
Nach der letzten Abstimmung mit Fr. Honal ist uns aufgefallen, dass die Implementierung der Index-Cards so nicht zu dem in der Doku beschriebenen, und somit gewünschten Use-Case passt. 

**Current Behaviour:**
Karten können nur von dem Ersteller eines Kurses angelegt werden. Somit sind alle Karten *kursweit* verfügbar. Die Kalkulation des Lernfortschritts zur Einordnung in die verschiedenen Lernkategorien basiert auf Attributen, die an der Index-Card gespeichert werden. Da die Karten *nicht Nutzerindividuell*, sondern kursweit verfügbar sind, ist der Fortschritt Kursweit gleich, sodass **kein eigener Fortschritt verfügbar ist**. 

**Intended Behaviour:**
Die Karten sollten, falls sie vom Ersteller eines Kurses angelegt werden, am besten auch kursweit verfügbar sein. Nutzer sollten außerdem eigene Karten anlegen können, die dann nur für sie verfügbar sind. Ebenfalls sollte der Lernfortschritt so berechnet werden, dass jeder Nutzer seinen eigenen Fortschritt besitzen kann.

**Comment by aaronschweig** [comment]
@jangruebener passt das so?

**Comment by jangruebener** [comment]
> @jangruebener passt das so?

Jup das passt aus meiner Sicht so. Schön beschrieben 👍🏻 Ich weiß, der Bugfix ist mit einigem Aufwand verbunden. Ich finde aber trotzdem, das wir ihn fixen sollten, da er ansonsten den ganzen Nutzen und das Konzept hinter den Karteikarten und unserer APP zu nichte macht
