### ISSUE TITLE
Präsentation für Projektabschluss erstellen

### ISSUE THREAD

**Issue by jangruebener** [DHBWMannheim/learninganalystics#44]

**Comment by jangruebener** [comment]
@aaronschweig @troykessler @Michi0400 @Patrickmischka @Ermodo 

Das Grundgerüst der Präsi ist erstellt. Habe euch einen Einladungslink zur Collaboration auf Discord geschickt.

**Comment by jangruebener** [comment]
Aufteilung:

![image](https://user-images.githubusercontent.com/43882912/111990334-7ea03480-8b13-11eb-84ac-0e597918b2cd.png)

**Comment by Ermodo** [comment]
@Patrickmischka Was machen wir mit den Anforderungen? Erwähnen wir die? Wenn ja kommt das in die Grundlagen?
